version: '3.9'

services:
  base-api:
    build:
      context: ../application/target
      dockerfile: ../../docker/Dockerfile
    container_name: base-api
    ports:
      - 8080:8080
    restart: always